package com.melib.Base;

/**
 * @file
 * @copyright defined in mechart_android/LICENSE
 */
public class EVENTID {
	public static int ADD = 0;
	public static int AUTOSIZECHANGED = 1;
	public static int BACKCOLORCHANGED = 2;
	public static int BACKIMAGECHANGED = 3;
	public static int CHAR = 4;
	public static int CLICK = 5;
	public static int COPY = 6;
	public static int CUT = 7;
	public static int DOCKCHANGED = 8;
	public static int DOUBLECLICK = 9;
	public static int DRAGBEGIN = 10;
	public static int DRAGEND = 11;
	public static int DRAGGING = 12;
	public static int ENABLECHANGED = 13;
	public static int FONTCHANGED = 14;
	public static int FORECOLORCHANGED = 15;
	public static int GOTFOCUS = 16;
	public static int INVOKE = 17;
	public static int KEYDOWN = 18;
	public static int KEYUP = 19;
	public static int LOAD = 20;
	public static int LOCATIONCHANGED = 21;
	public static int LOSTFOCUS = 22;
	public static int MARGINCHANGED = 23;
	public static int MOUSEDOWN = 24;
	public static int MOUSEENTER = 25;
	public static int MOUSELEAVE = 26;
	public static int MOUSEMOVE = 27;
	public static int MOUSEUP = 28;
	public static int MOUSEWHEEL = 29;
	public static int PADDINGCHANGED = 30;
	public static int PARENTCHANGED = 31;
	public static int PAINT = 32;
	public static int PAINTBORDER = 33;
	public static int PASTE = 34;
	public static int PREVIEWKEYDOWN = 35;
	public static int REGIONCHANGED = 36;
	public static int REMOVE = 37;
	public static int SIZECHANGED = 38;
	public static int TABINDEXCHANGED = 39;
	public static int TABSTOP = 40;
	public static int TABSTOPCHANGED = 41;
	public static int TEXTCHANGED = 42;
	public static int TIMER = 43;
	public static int VISIBLECHANGED = 44;
	public static int CHECKEDCHANGED = 45;
	public static int SELECTEDDAYCHANGED = 46;
	public static int GRIDCELLCLICK = 47;
	public static int GRIDCELLEDITBEGIN = 48;
	public static int GRIDCELLEDITEND = 49;
	public static int GRIDCELLMOUSEDOWN = 50;
	public static int GRIDCELLMOUSEENTER = 51;
	public static int GRIDCELLMOUSELEAVE = 52;
	public static int GRIDCELLMOUSEMOVE = 53;
	public static int GRIDCELLMOUSEUP = 54;
	public static int GRIDSELECTEDCELLSCHANGED = 55;
	public static int GRIDSELECTEDCOLUMNSSCHANGED = 56;
	public static int GRIDSELECTEDROWSCHANGED = 57;
	public static int MENUITEMCLICK = 58;
	public static int SELECTEDINDEXCHANGED = 59;
	public static int SELECTEDTABPAGECHANGED = 60;
	public static int SCROLLED = 61;
	public static int VALUECHANGED = 62;
	public static int WINDOWCLOSED = 63;
	public static int WINDOWCLOSING = 64;
	public static int PREVIEWSKEYEVENT = 65;
	public static int PREVIEWSMOUSEEVENT = 66;
	public static int TOUCHBEGIN = 10000;
	public static int TOUCHMOVE = 10001;
	public static int TOUCHEND = 10002;
	public static int TOUCHCANCEL = 10003;
	public static int USER = 100000;
}
